//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_COSTS
    {
        public decimal ID { get; set; }
        public decimal ID_CURRENT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string COSTS { get; set; }
    
        public virtual CURRENT_STATUS CURRENT_STATUS { get; set; }
    }
}
